# Good Morning All

In [1]:
# pip install numpy
import numpy
numpy.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
a = np.arange(1,12)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
a = np.arange(1,12,2)
a

array([ 1,  3,  5,  7,  9, 11])

In [16]:
a = np.linspace(2,50,25)
a

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
       28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50.])

In [20]:
a = np.ones(12)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
print(a.shape)
a.dtype

(13,)


dtype('float64')

In [31]:
a = np.zeros(13,dtype='int')
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
a = np.ones(13)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [1]:
import numpy as np
a = np.empty(13)
a

array([3.68150946e-316, 3.68214636e-316, 3.68214636e-316, 1.26974871e-321,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000])

In [4]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a = np.array([i for i in range(10)])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = np.array([[i for i in range(3)] for i in range(3)])
a

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [9]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [10]:
a.shape

(3, 2, 3)

In [19]:
a = np.array([1,2,3,4,5]).reshape(-1,1)
a

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [29]:
a = np.arange(12).reshape(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [30]:
a = np.linspace(1,10,10).reshape(5,2)
a

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [31]:
a = np.arange(16).reshape(2,4,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [38]:
a = np.ones((3,4,4))
a.shape

(3, 4, 4)

In [39]:
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [43]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a[1]

2

In [45]:
a[2:6]

array([3, 4, 5, 6])

In [46]:
a[-1]

9

In [47]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
for i in a:
    if i%2==0:
        print(i,end=' ')

2 4 6 8 

In [49]:
a[a%2==0]

array([2, 4, 6, 8])

In [64]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
a[1,1]

5

In [54]:
a[3,2]

14

In [55]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [70]:
a[2:4,2:4]

array([[10, 11],
       [14, 15]])

In [59]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a[9]

9

In [62]:
a[2:5]

array([2, 3, 4])

In [72]:
import random
a = random.randint(1,10)

In [74]:
a = np.random.randint(10)
a

0

In [75]:
a = np.arange(16).reshape(4,2,2)
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [76]:
a[0,1,1]

3

In [77]:
a[1,0,1]

5

In [82]:
a[0:2,0,:]

array([[0, 1],
       [4, 5]])

In [91]:
a = np.arange(10)
b = np.arange(10)
a+b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [90]:
l = [1,2,3,4,5]
li = [1,2,3,4]
l+li

[1, 2, 3, 4, 5, 1, 2, 3, 4]

In [93]:
a = np.arange(10)
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [94]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
for i in a.T:
    print(i)
    for j in i:
        print(j)

[0 4 8]
0
4
8
[1 5 9]
1
5
9
[ 2  6 10]
2
6
10
[ 3  7 11]
3
7
11


In [102]:
a = np.arange(16).reshape(4,2,2)
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [104]:
for i in a:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [108]:
a = input()
if '.' in a:
    print('float')
else:
    print('int')

2.0
float


In [ ]:
input:1 -  happy birthday
      2 - a # first
      3 - y # second
output : false