#### Data science libraries
- Numpy
- pandas 
- matplotlib

#Numpy
- pip install numpy  #command to install
- numerical python(scientific computing)
- more efficient than lists
- supports multidimensional data

In [5]:
import numpy as np

In [4]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [6]:
a=np.array([1,2,3,4,5,6]) 
a    #single dimensional data

array([1, 2, 3, 4, 5, 6])

In [9]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
a    #multidimensional data

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [10]:
a.shape # returns the no of rows and columns

(3, 3)

In [11]:
a.size   #returns the total no of values present in the array

9

In [14]:
a.ndim

2

In [15]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
np.ones((2,3),dtype=str)

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [20]:
np.ones((2,3),dtype=complex)

array([[1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j]])

In [21]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.zeros([2,3],dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
np.array([1,2,3,4,5,6]).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
help(np.random)

Help on package numpy.random in numpy:

NAME
    numpy.random

DESCRIPTION
    Random Number Generation
    
    ==================== =========================================================
    Utility functions
    random_sample        Uniformly distributed floats over ``[0, 1)``.
    random               Alias for `random_sample`.
    bytes                Uniformly distributed random bytes.
    random_integers      Uniformly distributed integers in a given range.
    permutation          Randomly permute a sequence / generate a random sequence.
    shuffle              Randomly permute a sequence in place.
    seed                 Seed the random number generator.
    choice               Random sample from 1-D array.
    
    ==================== =========================================================
    
    ==================== =========================================================
    Compatibility functions
    rand                 Uniformly distributed values.
    randn

In [25]:
np.random.randint(1,10)

9

In [26]:
np.random.random()

0.05523275963708796

In [27]:
np.random.random()

0.724515847395976

In [28]:
np.random.randint(1,100,10)

array([83, 31, 77, 92, 65, 27, 77, 76, 61, 20])

In [29]:
np.random.randint(1,100,10).reshape(5,2)

array([[94, 62],
       [62, 94],
       [52, 40],
       [79, 81],
       [72, 75]])

In [30]:
np.random.randint(1,100,10).reshape(2,5)

array([[ 6, 78, 19, 52, 95],
       [17,  5, 11, 19,  5]])

In [33]:
# Indexing
a=np.array([1,2,4,5,6,7])
a

array([1, 2, 4, 5, 6, 7])

In [34]:
a[0]

1

In [35]:
a[1]

2

In [6]:
b=np.random.randint(50,70,9).reshape(3,3)
b

array([[56, 54, 57],
       [67, 69, 61],
       [51, 52, 69]])

In [41]:
#b[rows,col]  
#specify rows and columns data in the form of slicing
b[0][1]

69

In [42]:
b[0,1]

69

In [45]:
b[0:1,1:2]  #slicing

array([[69]])

In [7]:
b

array([[56, 54, 57],
       [67, 69, 61],
       [51, 52, 69]])

In [24]:
b[0:2,1:3]
#b[rows,col]

array([[54, 57],
       [69, 61]])

In [9]:
#56  57
#51  69
b

array([[56, 54, 57],
       [67, 69, 61],
       [51, 52, 69]])

In [8]:
b[0:3:2,0:3:2]


array([[56, 57],
       [51, 69]])

In [10]:
b.max()

69

In [11]:
b.min()

51

In [12]:
b.mean()

59.55555555555556

In [13]:
b[0].mean()

55.666666666666664

In [15]:
b[1].mean()

65.66666666666667

In [16]:
b.sum()

536

In [17]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [18]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

In [21]:
np.arange(1,12,2).reshape(3,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [22]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [23]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])